
package VISTA.asesor;

import Modelo.entities.Cliente;
import Modelo.entities.Venta;

/**
 *
 * @author santiago
 */
public class administrarDeuda extends javax.swing.JFrame {

    Cliente clienteSeleccionado;
    Venta ventaSeleccionada;
    
    public administrarDeuda(Cliente clienteSeleccionado,Venta ventaSeleccionada) {
        initComponents();
        this.ventaSeleccionada = ventaSeleccionada;
        this.clienteSeleccionado = clienteSeleccionado;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnGuardarDeuda = new javax.swing.JButton();
        txtFechaDeuda = new javax.swing.JTextField();
        txtValorDeuda = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarPago = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMenu.setBackground(new java.awt.Color(49, 134, 181));
        btnMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 100, 40));

        btnGuardarDeuda.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardarDeuda.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardarDeuda.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarDeuda.setText("Guardar");
        btnGuardarDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDeudaActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 440, 100, 40));

        txtFechaDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaDeudaActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 370, 30));

        txtValorDeuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorDeudaActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 370, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registrarPago.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        jTabbedPane1.addTab("Registrar Deuda", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMostrarPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMostrarPago);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 680, 320));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestionarPago.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("Gestionar Deuda", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        btnMenu.setEnabled(false);

        menuAsesor masesor = new menuAsesor();
        masesor.setVisible(true);
        this.dispose();

        btnMenu.setEnabled(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnGuardarDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarDeudaActionPerformed

    private void txtFechaDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaDeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaDeudaActionPerformed

    private void txtValorDeudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorDeudaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorDeudaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarDeuda;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaMostrarPago;
    private javax.swing.JTextField txtFechaDeuda;
    private javax.swing.JTextField txtValorDeuda;
    // End of variables declaration//GEN-END:variables
}
