
package VISTA.asesor;

import CONTROLADOR.SessionManager;
import CONTROLADOR.gestionar.GestionarCliente;
import CONTROLADOR.gestionar.GestionarPago;
import CONTROLADOR.gestionar.GestionarVenta;
import Modelo.entities.Asesor;
import Modelo.entities.Cliente;
import Modelo.entities.Pago;
import Modelo.entities.Venta;
import Modelo.factory.I_PersistenciaFactory;
import Modelo.factory.PersistenciaFactory_inyect;
import java.sql.Date;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author juanc,Santiago
 */
public class administrarPago extends javax.swing.JFrame {

    GestionarPago gestiPago;
    GestionarVenta gestiVenta;
    Cliente clienteSeleccionado;
    Asesor asesorLogueado = SessionManager.getAsesorActual();
    Venta ventaSeleccionada;
    
    
    public administrarPago(Cliente clienteSeleccionado,Venta ventaSeleccionada) {
        initComponents();
        I_PersistenciaFactory factory = new PersistenciaFactory_inyect();
        this.gestiPago = new GestionarPago(factory);
        this.gestiVenta = new GestionarVenta(factory);
        this.ventaSeleccionada = ventaSeleccionada;
        this.clienteSeleccionado = clienteSeleccionado;
        cargarTxtValor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtFechaPago = new javax.swing.JTextField();
        txtValorPago = new javax.swing.JTextField();
        btnGuardarPago = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarPago = new javax.swing.JTable();
        btnEliminarPago = new javax.swing.JButton();
        btnEditarPago = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFechaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPagoActionPerformed(evt);
            }
        });
        jPanel1.add(txtFechaPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 370, 30));

        txtValorPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPagoActionPerformed(evt);
            }
        });
        jPanel1.add(txtValorPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 370, 30));

        btnGuardarPago.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardarPago.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarPago.setText("Guardar");
        btnGuardarPago.setBorder(null);
        btnGuardarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPagoActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 420, 90, 40));

        btnMenu.setBackground(new java.awt.Color(49, 134, 181));
        btnMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 100, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registrarPago.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 470));

        jTabbedPane1.addTab("Registar Pago", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMostrarPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMostrarPago);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 680, 320));

        btnEliminarPago.setBackground(new java.awt.Color(49, 134, 181));
        btnEliminarPago.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEliminarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPago.setText("Eliminar");
        btnEliminarPago.setBorder(null);
        btnEliminarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPagoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 90, 40));

        btnEditarPago.setBackground(new java.awt.Color(49, 134, 181));
        btnEditarPago.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnEditarPago.setForeground(new java.awt.Color(255, 255, 255));
        btnEditarPago.setText("Editar");
        btnEditarPago.setBorder(null);
        btnEditarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPagoActionPerformed(evt);
            }
        });
        jPanel2.add(btnEditarPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestionarPago.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 475));

        jTabbedPane1.addTab("Gestionar Pago", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarPagoActionPerformed

    private void btnEditarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPagoActionPerformed

    private void btnGuardarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPagoActionPerformed
        
        btnGuardarPago.setEnabled(false);
        
        int numero_pagos = gestiVenta.contarNPagos(ventaSeleccionada.getId_venta());
        if(numero_pagos < ventaSeleccionada.getNumero_coutas()){
            Date fecha = getFechaDesdeTxt();
            Long valor_pago = Long.parseLong(txtValorPago.getText());
        
            Pago pago = new Pago();
            pago.setFecha(fecha);
            pago.setValor_pago(valor_pago);
        
            pago.setAsesor(asesorLogueado);
            pago.setCliente(ventaSeleccionada.getCliente()); 
            pago.setVenta(ventaSeleccionada);
        
            ventaSeleccionada.getListaPagos().add(pago);
            asesorLogueado.getListaPagos().add(pago);
            ventaSeleccionada.getCliente().getListaPagos().add(pago);
        
            try {
                gestiPago.guardar(pago);
            } catch (Exception ex) {
                Logger.getLogger(pagoPrimeraCuota.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        
            menuAsesor masesor = new menuAsesor();
            masesor.setVisible(true);
            masesor.setLocationRelativeTo(null);
            this.dispose();
        }else{
            JOptionPane optionPane = new JOptionPane("No se pueden hacer mas pagos");
            optionPane.setMessageType(JOptionPane.ERROR_MESSAGE);
            JDialog dialog = optionPane.createDialog("ERROR");
            dialog.setAlwaysOnTop(true);dialog.setVisible(true);btnGuardarPago.setEnabled(true);
            return;
        }
        
        btnGuardarPago.setEnabled(true);
    }//GEN-LAST:event_btnGuardarPagoActionPerformed

    private void txtFechaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPagoActionPerformed

    private void txtValorPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorPagoActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        btnMenu.setEnabled(false);

        menuAsesor masesor = new menuAsesor();
        masesor.setVisible(true);
        this.dispose();

        btnMenu.setEnabled(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        cargarTabla();
    }//GEN-LAST:event_formWindowOpened

    private Date getFechaDesdeTxt() {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        String a = txtFechaPago.getText();
        if(a==null || a.isEmpty()){
            return null;
        }
        else{
            try {
                java.util.Date utilDate = formato.parse(a);
                return new Date(utilDate.getTime());
            } catch (ParseException e) {
            JOptionPane.showMessageDialog(null, "Formato de fecha incorrecto. Debe ser yyyy-MM-dd.", "Error", JOptionPane.ERROR_MESSAGE);
            return null;
            }
        }
    }

    public void cargarTxtValor(){
        
        txtFechaPago.setText(String.valueOf(ventaSeleccionada.getFecha()));
        Long valorCal = ventaSeleccionada.getPrecio_final()/ventaSeleccionada.getNumero_coutas();
        txtValorPago.setText(valorCal.toString());
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarPago;
    private javax.swing.JButton btnEliminarPago;
    private javax.swing.JButton btnGuardarPago;
    private javax.swing.JButton btnMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaMostrarPago;
    private javax.swing.JTextField txtFechaPago;
    private javax.swing.JTextField txtValorPago;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() {
        DefaultTableModel modeloTabla  = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable (int row,int column){
                return false;
            }
        };
        
        String titulos[] = {"Id Pago","Valor Pago","Nombre Cliente","Subsidio","Num Coutas","Intereses","Precio Total"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        Long ced = clienteSeleccionado.getCedula();
        Long id = ventaSeleccionada.getId_venta();
        List<Pago> listaPagos = gestiPago.traerVentaPago(id);
        
        if(listaPagos != null){
            for(Pago pago: listaPagos){
                Object[] objeto ={pago.getId_pago(),pago.getValor_pago(),
                    pago.getCliente().getNombre(),pago.getCliente().getSubsidio_ministerio(),
                    pago.getVenta().getNumero_coutas(),pago.getVenta().getIntereses(),
                    pago.getVenta().getPrecio_final()};
                modeloTabla.addRow(objeto);
            }
        }
        
        tablaMostrarPago.setModel(modeloTabla);
        tablaMostrarPago.setRowHeight(30);
        
        TableColumnModel columnModel = tablaMostrarPago.getColumnModel();
        columnModel.getColumn(0).setMinWidth(0);
        columnModel.getColumn(0).setMaxWidth(0);
        columnModel.getColumn(0).setWidth(0);
    }
}
