
package VISTA.asesor;

import CONTROLADOR.gestionar.GestionarVenta;
import Modelo.entities.Apartamento;
import Modelo.entities.Cliente;
import Modelo.entities.Venta;
import Modelo.factory.I_PersistenciaFactory;
import Modelo.factory.PersistenciaFactory_inyect;
import java.awt.Font;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Santiago
 */
public class AptosVendidos extends javax.swing.JFrame {

    Cliente clienteSeleccionado;
    GestionarVenta gestiVenta;
    
    public AptosVendidos(Cliente clienteSeleccionado) {
        I_PersistenciaFactory factory = new PersistenciaFactory_inyect();
        this.gestiVenta = new GestionarVenta(factory);
        this.clienteSeleccionado = clienteSeleccionado;
        initComponents();
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMostrarAptosVendidos = new javax.swing.JTable();
        btnMenu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaMostrarAptosVendidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaMostrarAptosVendidos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 850, 340));

        btnMenu1.setBackground(new java.awt.Color(49, 134, 181));
        btnMenu1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMenu1.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu1.setText("Volver");
        btnMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/apartamentos vendidos.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu1ActionPerformed
        
        administrarVenta adminVenta = new administrarVenta(clienteSeleccionado);
        adminVenta.setVisible(true);
        adminVenta.setLocationRelativeTo(null);
        this.dispose();
        
    }//GEN-LAST:event_btnMenu1ActionPerformed

    public void cargarTabla(){
        
        DefaultTableModel modeloTabla  = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable (int row,int column){
                return false;
            }
        };
        
        String titulos[] = {"Nombre Proyecto","Num Torre","Num Apto","Valor Apto","Matricula","Fecha Escritura",
            "Area","Tipo Unidad"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        Long ced_cliente = clienteSeleccionado.getCedula();
        List<Venta> listaVentas = gestiVenta.obtenerVentaCliente(ced_cliente);
        System.out.println(listaVentas);
        for(Venta venta: listaVentas){
            Long id_venta = venta.getId_venta();
            System.out.println("El id de la venta es "+id_venta +"y la cedula es: " + ced_cliente);    
            List<Apartamento> listaAptosVendidos = gestiVenta.obtenerAptosVendidos(id_venta,ced_cliente);
            System.out.println(listaAptosVendidos);
            for (Apartamento apto : listaAptosVendidos) {
                Object[] objeto ={apto.getTorre().getProyecto().getNombre_proyecto(),
                apto.getTorre().getNumero_torre(),
                apto.getNum_apartamento(),
                apto.getValor_apartamento(),
                apto.getMatricula(),
                apto.getFecha_escritura(),
                apto.getArea(),
                apto.getTipo_unidad()};
                modeloTabla.addRow(objeto);
            }
        }
        
        tablaMostrarAptosVendidos.setModel(modeloTabla);
        tablaMostrarAptosVendidos.setRowHeight(30);
        tablaMostrarAptosVendidos.getTableHeader().setReorderingAllowed(false);
        
        tablaMostrarAptosVendidos.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 14));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaMostrarAptosVendidos;
    // End of variables declaration//GEN-END:variables
}
