/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

import CONTROLADOR.GestionarProyecto;
import CONTROLADOR.GestionarTorre;
import Modelo.entities.Apartamento;
import Modelo.entities.Proyecto;
import Modelo.entities.Torre;
import java.util.ArrayList;

/**
 *
 * @author juanc
 */
public class crearProyecto2 extends javax.swing.JFrame {
    
    GestionarTorre gestiTorre;
    GestionarProyecto gestiProyecto;
    Proyecto proyectoActual;
    /**
     * Creates new form crearProyecto2
     */
    public crearProyecto2(GestionarProyecto gestiProyecto,Proyecto proyectoActual) {
        initComponents();
        this.gestiTorre = new GestionarTorre();
        this.gestiProyecto = gestiProyecto;
        this.proyectoActual = proyectoActual;
        setSize(912, 510); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguienteCrearTorre = new javax.swing.JButton();
        txtNumeroTorre = new javax.swing.JTextField();
        txtNumeroDeApartamentos = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguienteCrearTorre.setBackground(new java.awt.Color(49, 134, 181));
        btnSiguienteCrearTorre.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSiguienteCrearTorre.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteCrearTorre.setText("Siguiente");
        btnSiguienteCrearTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteCrearTorreActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguienteCrearTorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 110, 40));

        txtNumeroTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTorreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroTorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 290, 30));

        txtNumeroDeApartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeApartamentosActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroDeApartamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 290, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crearProyecto2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTorreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTorreActionPerformed

    private void txtNumeroDeApartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeApartamentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeApartamentosActionPerformed

    private void btnSiguienteCrearTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteCrearTorreActionPerformed
        
        btnSiguienteCrearTorre.setEnabled(false);
        
        int numeroTorre = Integer.parseInt(txtNumeroTorre.getText());
        int numeroApartamentos = Integer.parseInt(txtNumeroDeApartamentos.getText());
        
        Torre torre = new Torre();
        torre.setNumero_torre(numeroTorre);
        torre.setNumero_apartamentos(numeroApartamentos);
        torre.setProyecto(proyectoActual);
        torre.setListaApartamentos(new ArrayList<Apartamento>());
        
        //añade la torre a la lista torre del proyecto que cree anteriormente
        proyectoActual.getListaTorres().add(torre);
        Torre torreActual = gestiTorre.guardar(torre);
        
        crearProyecto3 crearProyectoApt = new crearProyecto3(gestiTorre,torreActual);
        crearProyectoApt.setVisible(true);
        crearProyectoApt.setLocationRelativeTo(null);
        this.dispose();
        
        btnSiguienteCrearTorre.setEnabled(true);
    }//GEN-LAST:event_btnSiguienteCrearTorreActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguienteCrearTorre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumeroDeApartamentos;
    private javax.swing.JTextField txtNumeroTorre;
    // End of variables declaration//GEN-END:variables
}
