/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VISTA;

/**
 *
 * @author juanc
 */
public class crearProyecto3 extends javax.swing.JFrame {

    /**
     * Creates new form crearProyecto3
     */
    public crearProyecto3() {
        initComponents();
        setSize(912, 510); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroDeTorres = new javax.swing.JTextField();
        txtNombreProyecto1 = new javax.swing.JTextField();
        txtNumeroDeTorres1 = new javax.swing.JTextField();
        txtNombreProyecto2 = new javax.swing.JTextField();
        txtNumeroDeTorres2 = new javax.swing.JTextField();
        txtNumeroDeTorres3 = new javax.swing.JTextField();
        btnSiguienteCrearProyecto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeroDeTorres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeTorresActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroDeTorres, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 290, 30));

        txtNombreProyecto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProyecto1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreProyecto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 290, 30));

        txtNumeroDeTorres1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeTorres1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroDeTorres1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 290, 30));

        txtNombreProyecto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProyecto2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreProyecto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 320, 290, 30));

        txtNumeroDeTorres2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeTorres2ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroDeTorres2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 440, 240, 30));

        txtNumeroDeTorres3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeTorres3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroDeTorres3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 290, 30));

        btnSiguienteCrearProyecto.setBackground(new java.awt.Color(49, 134, 181));
        btnSiguienteCrearProyecto.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSiguienteCrearProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteCrearProyecto.setText("Guardar");
        btnSiguienteCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteCrearProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguienteCrearProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crearProyecto3.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDeTorresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeTorresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeTorresActionPerformed

    private void btnSiguienteCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteCrearProyectoActionPerformed

    }//GEN-LAST:event_btnSiguienteCrearProyectoActionPerformed

    private void txtNombreProyecto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProyecto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProyecto1ActionPerformed

    private void txtNumeroDeTorres1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeTorres1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeTorres1ActionPerformed

    private void txtNombreProyecto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProyecto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProyecto2ActionPerformed

    private void txtNumeroDeTorres2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeTorres2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeTorres2ActionPerformed

    private void txtNumeroDeTorres3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeTorres3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroDeTorres3ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguienteCrearProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNombreProyecto1;
    private javax.swing.JTextField txtNombreProyecto2;
    private javax.swing.JTextField txtNumeroDeTorres;
    private javax.swing.JTextField txtNumeroDeTorres1;
    private javax.swing.JTextField txtNumeroDeTorres2;
    private javax.swing.JTextField txtNumeroDeTorres3;
    // End of variables declaration//GEN-END:variables
}
