/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package VISTA;

/**
 *
 * @author juanc
 */
public class menuAdmin extends javax.swing.JFrame {


    /**
     * Creates new form adminProyecto
     */
    public menuAdmin() {
        initComponents();
        setSize(912, 510); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdministrarProyecto = new javax.swing.JButton();
        btnAdministrarAsesor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdministrarProyecto.setBackground(new java.awt.Color(255, 255, 255));
        btnAdministrarProyecto.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAdministrarProyecto.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarProyecto.setText("ADMINISTRAR PROYECTO");
        btnAdministrarProyecto.setBorder(null);
        btnAdministrarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 230, 40));

        btnAdministrarAsesor.setBackground(new java.awt.Color(255, 255, 255));
        btnAdministrarAsesor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnAdministrarAsesor.setForeground(new java.awt.Color(0, 0, 0));
        btnAdministrarAsesor.setText("ADMINISTRAR ASESOR");
        btnAdministrarAsesor.setBorder(null);
        btnAdministrarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdministrarAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 330, 210, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/menu.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarProyectoActionPerformed
        
        
    }//GEN-LAST:event_btnAdministrarProyectoActionPerformed

    private void btnAdministrarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarAsesorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarAsesor;
    private javax.swing.JButton btnAdministrarProyecto;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
