
package VISTA.admin;

import CONTROLADOR.GestionarAsesor;
import Modelo.entities.Asesor;
import Modelo.entities.Correo;
import Modelo.entities.Pago;
import Modelo.entities.Telefono;
import Modelo.entities.Venta;
import Modelo.factory.I_PersistenciaFactory;
import Modelo.factory.PersistenciaFactory_inyect;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author CLAUDIA
 */
public class AdministrarAsesor extends javax.swing.JFrame {

    GestionarAsesor gestiAsesor;
    
    public AdministrarAsesor() {
        I_PersistenciaFactory factory = new PersistenciaFactory_inyect();
        this.gestiAsesor = new GestionarAsesor(factory);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txtTelefonoAsesorReg = new javax.swing.JTextField();
        txtNombreAsesor = new javax.swing.JTextField();
        txtCedulaAsesor = new javax.swing.JTextField();
        txtDireccionAsesor = new javax.swing.JTextField();
        txtCorreoAsesorReg = new javax.swing.JTextField();
        btnSiguienteAsesor = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnGuardarAsesor = new javax.swing.JButton();
        btnGuardarAsesor1 = new javax.swing.JButton();
        btnGuardarAsesor2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTelefonoAsesorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoAsesorRegActionPerformed(evt);
            }
        });
        jPanel1.add(txtTelefonoAsesorReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 290, 30));

        txtNombreAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAsesorActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 290, 30));

        txtCedulaAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaAsesorActionPerformed(evt);
            }
        });
        jPanel1.add(txtCedulaAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, 290, 30));

        txtDireccionAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionAsesorActionPerformed(evt);
            }
        });
        jPanel1.add(txtDireccionAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 290, 30));

        txtCorreoAsesorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoAsesorRegActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreoAsesorReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 290, 30));

        btnSiguienteAsesor.setBackground(new java.awt.Color(49, 134, 181));
        btnSiguienteAsesor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSiguienteAsesor.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteAsesor.setText("Siguiente");
        btnSiguienteAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteAsesorActionPerformed(evt);
            }
        });
        jPanel1.add(btnSiguienteAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 110, 40));

        btnMenu.setBackground(new java.awt.Color(49, 134, 181));
        btnMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 100, 40));

        jTabbedPane1.addTab("Registrar Asesor", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 620, 310));

        btnGuardarAsesor.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardarAsesor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardarAsesor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAsesor.setText("Eliminar");
        btnGuardarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsesorActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 110, 40));

        btnGuardarAsesor1.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardarAsesor1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardarAsesor1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAsesor1.setText("Agregar");
        btnGuardarAsesor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsesor1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarAsesor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 110, 40));

        btnGuardarAsesor2.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardarAsesor2.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardarAsesor2.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAsesor2.setText("Editar");
        btnGuardarAsesor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsesor2ActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardarAsesor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 110, 40));

        jTabbedPane1.addTab("Gestionar Asesor", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoAsesorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoAsesorRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoAsesorRegActionPerformed

    private void txtNombreAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAsesorActionPerformed

    private void txtCedulaAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaAsesorActionPerformed

    private void txtDireccionAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionAsesorActionPerformed

    private void txtCorreoAsesorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoAsesorRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoAsesorRegActionPerformed

    private void btnSiguienteAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteAsesorActionPerformed

        btnSiguienteAsesor.setEnabled(false);

        String nombreAsesor = txtNombreAsesor.getText();
        int cedulaAsesor = Integer.parseInt(txtCedulaAsesor.getText());
        String direccionAsesor = txtDireccionAsesor.getText();
        String correoAsesor = txtCorreoAsesorReg.getText();
        int telefonoAsesor = Integer.parseInt(txtTelefonoAsesorReg.getText());
        
        Asesor asesor = new Asesor();Correo correo = new Correo();
        Telefono telefono = new Telefono();
        asesor.setNombre(nombreAsesor);
        asesor.setCedula(cedulaAsesor);
        asesor.setDireccion(direccionAsesor);
        asesor.setListaVentas(new ArrayList<Venta>());
        asesor.setListaPagos(new ArrayList<Pago>());
        asesor.setListaTelefonosCliente(new ArrayList<Telefono>());
        asesor.setListaCorreoCliente(new ArrayList<Correo>());
        
        Asesor asesorSelect = null;
        try {
            asesorSelect = gestiAsesor.guardar(asesor);
        } catch (Exception ex) {
            Logger.getLogger(AdministrarAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        correo.setCorreo(correoAsesor);
        correo.setAsesor(asesor);
        
        try {
            gestiAsesor.guardarCorr(correo);
        } catch (Exception ex) {
            Logger.getLogger(AdministrarAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        telefono.setTelefono(telefonoAsesor);
        telefono.setAsesor(asesor);
        
        try {
            gestiAsesor.guardarTel(telefono);
        } catch (Exception ex) {
            Logger.getLogger(AdministrarAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        asesor.getListaCorreoCliente().add(correo);
        asesor.getListaTelefonosCliente().add(telefono);
        
        UsuarioAsesor usuAsesor = new UsuarioAsesor(asesorSelect);
        usuAsesor.setVisible(true);
        usuAsesor.setLocationRelativeTo(null);
        this.dispose();

        btnSiguienteAsesor.setEnabled(true);
    }//GEN-LAST:event_btnSiguienteAsesorActionPerformed

    private void btnGuardarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsesorActionPerformed

        btnGuardarAsesor.setEnabled(false);

        btnGuardarAsesor.setEnabled(true);
    }//GEN-LAST:event_btnGuardarAsesorActionPerformed

    private void btnGuardarAsesor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsesor1ActionPerformed

        btnGuardarAsesor.setEnabled(false);

        btnGuardarAsesor.setEnabled(true);
    }//GEN-LAST:event_btnGuardarAsesor1ActionPerformed

    private void btnGuardarAsesor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsesor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarAsesor2ActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        btnMenu.setEnabled(false);

        menuAdmin mAdmin = new menuAdmin();
        mAdmin.setVisible(true);
        this.dispose();

        btnMenu.setEnabled(true);
    }//GEN-LAST:event_btnMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAsesor;
    private javax.swing.JButton btnGuardarAsesor1;
    private javax.swing.JButton btnGuardarAsesor2;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSiguienteAsesor;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCedulaAsesor;
    private javax.swing.JTextField txtCorreoAsesorReg;
    private javax.swing.JTextField txtDireccionAsesor;
    private javax.swing.JTextField txtNombreAsesor;
    private javax.swing.JTextField txtTelefonoAsesorReg;
    // End of variables declaration//GEN-END:variables
}
