
package VISTA.admin;

import CONTROLADOR.GestionarAsesor;
import Modelo.entities.Asesor;
import Modelo.factory.I_PersistenciaFactory;
import Modelo.factory.PersistenciaFactory_inyect;

/**
 *
 * @author Santiago
 */
public class EditarAsesor extends javax.swing.JFrame {

    GestionarAsesor gestiAsesor;
    private Asesor asesor;
    
    public EditarAsesor(int ced_asesor) {
        I_PersistenciaFactory factory = new PersistenciaFactory_inyect();
        this.gestiAsesor = new GestionarAsesor(factory);
        initComponents();
        cargaDatos(ced_asesor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreAsesor = new javax.swing.JTextField();
        txtCedulaAsesor = new javax.swing.JTextField();
        txtDireccionAsesor = new javax.swing.JTextField();
        txtCorreoAsesorReg = new javax.swing.JTextField();
        txtTelefonoAsesorReg = new javax.swing.JTextField();
        btnSiguienteAsesor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 290, 20));

        txtCedulaAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCedulaAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(txtCedulaAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 290, -1));

        txtDireccionAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(txtDireccionAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 290, 20));

        txtCorreoAsesorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoAsesorRegActionPerformed(evt);
            }
        });
        getContentPane().add(txtCorreoAsesorReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 290, 20));

        txtTelefonoAsesorReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoAsesorRegActionPerformed(evt);
            }
        });
        getContentPane().add(txtTelefonoAsesorReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 290, 20));

        btnSiguienteAsesor.setBackground(new java.awt.Color(49, 134, 181));
        btnSiguienteAsesor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSiguienteAsesor.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteAsesor.setText("Siguiente");
        btnSiguienteAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguienteAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 360, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/registrarAsesor.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteAsesorActionPerformed

        btnSiguienteAsesor.setEnabled(false);
        /*
        String nombreAsesor = txtNombreAsesor.getText();
        int cedulaAsesor = Integer.parseInt(txtCedulaAsesor.getText());
        String direccionAsesor = txtDireccionAsesor.getText();
        String correoAsesor = txtCorreoAsesorReg.getText();
        int telefonoAsesor = Integer.parseInt(txtTelefonoAsesorReg.getText());

        Asesor asesor = new Asesor();Correo correo = new Correo();
        Telefono telefono = new Telefono();
        asesor.setNombre(nombreAsesor);
        asesor.setCedula(cedulaAsesor);
        asesor.setDireccion(direccionAsesor);
        asesor.setListaVentas(new ArrayList<Venta>());
        asesor.setListaPagos(new ArrayList<Pago>());
        asesor.setListaTelefonos(new ArrayList<Telefono>());
        asesor.setListaCorreos(new ArrayList<Correo>());

        Asesor asesorSelect = null;
        try {
            asesorSelect = gestiAsesor.guardar(asesor);
        } catch (Exception ex) {
            Logger.getLogger(administrarAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }

        correo.setCorreo(correoAsesor);
        correo.setAsesor(asesor);

        try {
            gestiAsesor.guardarCorr(correo);
        } catch (Exception ex) {
            Logger.getLogger(administrarAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }

        telefono.setTelefono(telefonoAsesor);
        telefono.setAsesor(asesor);

        try {
            gestiAsesor.guardarTel(telefono);
        } catch (Exception ex) {
            Logger.getLogger(administrarAsesor.class.getName()).log(Level.SEVERE, null, ex);
        }

        asesor.getListaCorreos().add(correo);
        asesor.getListaTelefonos().add(telefono);

        UsuarioAsesor usuAsesor = new UsuarioAsesor(asesorSelect);
        usuAsesor.setVisible(true);
        usuAsesor.setLocationRelativeTo(null);
        this.dispose();
        */
        btnSiguienteAsesor.setEnabled(true);
    }//GEN-LAST:event_btnSiguienteAsesorActionPerformed

    private void txtNombreAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreAsesorActionPerformed

    private void txtCedulaAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCedulaAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCedulaAsesorActionPerformed

    private void txtDireccionAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionAsesorActionPerformed

    private void txtCorreoAsesorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoAsesorRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoAsesorRegActionPerformed

    private void txtTelefonoAsesorRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoAsesorRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoAsesorRegActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSiguienteAsesor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtCedulaAsesor;
    private javax.swing.JTextField txtCorreoAsesorReg;
    private javax.swing.JTextField txtDireccionAsesor;
    private javax.swing.JTextField txtNombreAsesor;
    private javax.swing.JTextField txtTelefonoAsesorReg;
    // End of variables declaration//GEN-END:variables

    private void cargaDatos(int ced_asesor) {
        this.asesor = gestiAsesor.buscarPorId(ced_asesor);
        
        txtNombreAsesor.setText(asesor.getNombre());
        txtCedulaAsesor.setText(String.valueOf(asesor.getCedula()));
        txtDireccionAsesor.setText(asesor.getDireccion());
        //txtCorreoAsesorReg.set
        //txtTelefonoAsesorReg
    }
}
