
package VISTA.admin;

import CONTROLADOR.gestionar.GestionarTorre;
import Modelo.entities.Torre;
import Modelo.factory.I_PersistenciaFactory;
import Modelo.factory.PersistenciaFactory_inyect;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Santiago
 */
public class EditarTorre extends javax.swing.JFrame {

    private GestionarTorre gestiApto;
    private Torre torre;
    
    public EditarTorre(Long id_torre) {
        I_PersistenciaFactory factory = new PersistenciaFactory_inyect();
        this.gestiApto = new GestionarTorre(factory);
        initComponents();
        cargarDatos(id_torre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroTorre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNumeroTorre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroTorreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroTorre, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 290, 30));

        btnGuardar.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardar.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EditarTorre.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroTorreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroTorreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroTorreActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        btnGuardar.setEnabled(false);

        int numeroTorre = Integer.parseInt(txtNumeroTorre.getText());

        try {
            gestiApto.editar(torre,numeroTorre);
        } catch (Exception ex) {
            Logger.getLogger(EditarTorre.class.getName()).log(Level.SEVERE, null, ex);
        }

        //poner mensaje de que salio bien

        menuAdmin mAdmin = new menuAdmin();
        mAdmin.setVisible(true);
        mAdmin.setLocationRelativeTo(null);
        this.dispose();

        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_btnGuardarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNumeroTorre;
    // End of variables declaration//GEN-END:variables

    private void cargarDatos(Long id_torre) {
        
        this.torre = gestiApto.buscarPorId(id_torre);
        
        txtNumeroTorre.setText(String.valueOf(torre.getNumero_torre()));
    }
}
