
package VISTA.admin;

import VISTA.admin.menuAdmin;
import VISTA.admin.administrarTorre;
import CONTROLADOR.gestionar.GestionarProyecto;
import Modelo.entities.Proyecto;
import Modelo.factory.I_PersistenciaFactory;
import Modelo.factory.PersistenciaFactory_inyect;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author juanc,Santiago
 */
public class torreSeleccionarProyecto extends javax.swing.JFrame {

    GestionarProyecto gestiProyecto;
    
    public torreSeleccionarProyecto() {
        I_PersistenciaFactory factory = new PersistenciaFactory_inyect();
        this.gestiProyecto = new GestionarProyecto(factory);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSiguienteSeleccionarProyecto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSeleccionarProyecto = new javax.swing.JTable();
        btnMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSiguienteSeleccionarProyecto.setBackground(new java.awt.Color(49, 134, 181));
        btnSiguienteSeleccionarProyecto.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnSiguienteSeleccionarProyecto.setForeground(new java.awt.Color(255, 255, 255));
        btnSiguienteSeleccionarProyecto.setText("Siguiente");
        btnSiguienteSeleccionarProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteSeleccionarProyectoActionPerformed(evt);
            }
        });
        getContentPane().add(btnSiguienteSeleccionarProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 110, 40));

        tablaSeleccionarProyecto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaSeleccionarProyecto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 490, 290));

        btnMenu.setBackground(new java.awt.Color(49, 134, 181));
        btnMenu.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("Menu");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/gestionarTorre.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteSeleccionarProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteSeleccionarProyectoActionPerformed

        btnSiguienteSeleccionarProyecto.setEnabled(false);

        if(tablaSeleccionarProyecto.getRowCount() > 0){
            if(tablaSeleccionarProyecto.getSelectedRow() != -1){
                
                Long id_proyecto = Long.parseLong(String.valueOf(tablaSeleccionarProyecto.getValueAt(tablaSeleccionarProyecto.getSelectedRow(), 0)));

                Proyecto proyectoSeleccionado = null;
                try {
                    proyectoSeleccionado = gestiProyecto.buscarPorId(id_proyecto);
                } catch (Exception ex) {
                    Logger.getLogger(torreSeleccionarProyecto.class.getName()).log(Level.SEVERE, null, ex);
                }
                administrarTorre adminTorre = new administrarTorre(proyectoSeleccionado);
                adminTorre.setVisible(true);
                adminTorre.setLocationRelativeTo(null);
                this.dispose();
                
            }
        }

        btnSiguienteSeleccionarProyecto.setEnabled(true);
    }//GEN-LAST:event_btnSiguienteSeleccionarProyectoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
        try {
            cargarTabla();
        } catch (Exception ex) {
            Logger.getLogger(torreSeleccionarProyecto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        btnMenu.setEnabled(false);

        menuAdmin mAdmin = new menuAdmin();
        mAdmin.setVisible(true);
        this.dispose();

        btnMenu.setEnabled(true);
    }//GEN-LAST:event_btnMenuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnSiguienteSeleccionarProyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSeleccionarProyecto;
    // End of variables declaration//GEN-END:variables

    private void cargarTabla() throws Exception {

        DefaultTableModel modeloTabla  = new DefaultTableModel(){
            
            @Override
            public boolean isCellEditable (int row,int column){
                return false;
            }
        };
        
        String titulos[] = {"Numero Proyecto","Nombre Proyecto"};
        modeloTabla.setColumnIdentifiers(titulos);
        
        List<Proyecto> listaProyectos = gestiProyecto.obtenerProyectosAdmin();
        
        if(listaProyectos != null){
            for(Proyecto proyect: listaProyectos){
                Object[] objeto ={proyect.getId_proyecto(),proyect.getNombre_proyecto()};
                modeloTabla.addRow(objeto);
            }
        }
        
        tablaSeleccionarProyecto.setModel(modeloTabla);
        tablaSeleccionarProyecto.getTableHeader().setReorderingAllowed(false);
        
        TableColumnModel columnModel = tablaSeleccionarProyecto.getColumnModel();
        columnModel.getColumn(0).setMinWidth(0);
        columnModel.getColumn(0).setMaxWidth(0);
        columnModel.getColumn(0).setWidth(0);
        
        //Espaciado de filas
        tablaSeleccionarProyecto.setRowHeight(30); 
    }
}
