
package VISTA.admin;

/**
 *
 * @author CLAUDIA
 */
public class UsuarioAsesor extends javax.swing.JFrame {

    /**
     * Creates new form UsuarioAsesor
     */
    public UsuarioAsesor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGuardarAsesor = new javax.swing.JButton();
        txtContraseñaAsesor = new javax.swing.JTextField();
        txtUsuarioAsesor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarAsesor.setBackground(new java.awt.Color(49, 134, 181));
        btnGuardarAsesor.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        btnGuardarAsesor.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardarAsesor.setText("Guardar");
        btnGuardarAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, 110, 40));

        txtContraseñaAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContraseñaAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(txtContraseñaAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 230, 290, 30));

        txtUsuarioAsesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAsesorActionPerformed(evt);
            }
        });
        getContentPane().add(txtUsuarioAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 290, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAsesorActionPerformed

        btnGuardarAsesor.setEnabled(false);

        btnGuardarAsesor.setEnabled(true);
    }//GEN-LAST:event_btnGuardarAsesorActionPerformed

    private void txtContraseñaAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContraseñaAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContraseñaAsesorActionPerformed

    private void txtUsuarioAsesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAsesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAsesorActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarAsesor;
    private javax.swing.JTextField txtContraseñaAsesor;
    private javax.swing.JTextField txtUsuarioAsesor;
    // End of variables declaration//GEN-END:variables
}
